name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR title follows Conventional Commits
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          test
          chore
          perf
          ci
          build
          revert
        scopes: |
          cli
          config
          templates
          render
          ingest
          ai
          validate
          pdf
          ux
          devops
          release
          core
          api
        requireScope: false
        subjectPattern: ^(?![A-Z]).+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          doesn't match the configured pattern. Please ensure that the subject
          doesn't start with an uppercase character.
        ignoreLabels: |
          bot
          ignore-semantic-pull-request
        headerPattern: '^(\w+)(?:\((\w+)\))?: (.+)$'
        headerPatternCorrespondence: type, scope, subject
        wip: false
        validateSingleCommit: false
        validateSingleCommitMatchesPrTitle: false